# Render configuration file for automatic deployment
services:
  - type: web
    name: telegram-bot-enhanced
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install .
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: FOLLOWING_CHANNEL
        value: "@allinonemaker"
      - key: AUTO_CLEANUP_HOURS
        value: "12"
      - key: DEVELOPER_CREDIT
        value: "@Alcboss112"
      - key: INSTAGRAM_SESSIONID
        sync: false
      - key: TWITTER_AUTH_TOKEN
        sync: false
      - key: FACEBOOK_CUSER
        sync: false
      - key: FACEBOOK_XS
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELETHON_BOT_TOKEN
        sync: false
      # Optional helper APIs for fallback downloads
      - key: TIKTOK_API
        value: "https://www.tikwm.com/api/?url="
      - key: FACEBOOK_API
        value: "https://myapi-2f5b.onrender.com/fbvideo/search?url="
      - key: TWITTER_API
        value: "https://twitsave.com/info?url="
    healthCheckPath: /
