services:
  - type: web
    name: all-in-one-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

  - type: worker
    name: all-in-one-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
