services:
  - type: web
    name: all-downloader-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: INSTAGRAM_SESSIONID
        value: "<your_instagram_sessionid>"
      - key: FACEBOOK_CUSER
        value: "<your_facebook_cuser>"
      - key: FACEBOOK_XS
        value: "<your_facebook_xs>"
      - key: TWITTER_COOKIES
        value: "<your_twitter_cookies>"

  - type: worker
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "<your_bot_token>"
      - key: TELEGRAM_CHAT_ID
        value: "<your_chat_id>"
      - key: INSTAGRAM_SESSIONID
        value: "<your_instagram_sessionid>"
      - key: FACEBOOK_CUSER
        value: "<your_facebook_cuser>"
      - key: FACEBOOK_XS
        value: "<your_facebook_xs>"
      - key: TWITTER_COOKIES
        value: "<your_twitter_cookies>"
